language: python
python:
  - "3.11"

services:
  - docker

env:
  global:
    - DOCKER_IMAGE_NAME=$DOCKER_USERNAME/secret-device
    - DOCKER_TAG=latest

before_install:
  - docker login -u $DOCKER_USERNAME_ENCRYPTED -p $DOCKER_PASSWORD_ENCRYPTED

install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov

script:
  # Run tests
  - pytest --cov=app test/
  # Build Docker image
  - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG .
  # Test Docker container
  - docker run -d -p 5000:5000 --name test-container $DOCKER_IMAGE_NAME:$DOCKER_TAG
  - sleep 5
  - curl -f http://localhost:5000/health
  - docker stop test-container
  - docker rm test-container

after_success:
  # Push Docker image to Docker Hub
  - docker push $DOCKER_IMAGE_NAME:$DOCKER_TAG
  # Update health endpoint with Docker Hub link
  - echo "DOCKER_HUB_LINK=https://hub.docker.com/r/$DOCKER_IMAGE_NAME" >> .env
  - echo "GITHUB_PROJECT_LINK=https://github.com/$TRAVIS_REPO_SLUG" >> .env
