version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
